import React from "react";
import styles from "./page.module.css";
import Image from "next/image";
import Button from "@/components/Button/Button";

export const metadata = {
  title: "Jahir Dev Contact information",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>Let's Keep in touch</h1>
      <div className={styles.content}>
        <div className={styles.imgContainer}>
          <Image
            src="/contact.png"
            alt="Contact image"
            fill={true}
            className={styles.img}
          />
        </div>
        <form className={styles.form}>
          <input text="text" placeholder="name" className={styles.input} />
          <input text="text" placeholder="email" className={styles.input} />
          <textarea 
          className={styles.textArea}
          placeholder="message"
          cols="30"
          rows="10"
          ></textarea>
          <Button text="send" url="#"/>
        </form>
      </div>
    </div>
  );
};

export default Contact;
